### ISSUE TITLE
Is passable add panGestures?

### ISSUE THREAD

**Issue by LeonGuo30848** [eldade/ios_metal_bezier_renderer#4]
when I use it on UIPanGestureRecognizer,UIGestureRecognizerStateBegan,UIGestureRecognizerStateChanged ,every status push one point, and draw line or curve,cant control the point for every triangle, the look like aliasing Lins

**Comment by eldade** [comment]
Not sure I understand. You're trying to control the curves using a gesture recognizer? And what is the issue you're seeing? Can you send a screenshot?

**Comment by LeonGuo30848** [comment]
![WechatIMG3](https://user-images.githubusercontent.com/38343165/58697410-0d3a4380-83cc-11e9-97bb-abc43ed1097a.jpeg)
I was try line like this, then how can I fill it ,then make it like line

**Comment by LeonGuo30848** [comment]
`vertex Point vertex_point_func(constant Point *points [[ buffer(0) ]],
                               constant Uniforms &uniforms [[ buffer(1) ]],
                               constant Transform &transform [[ buffer(2) ]],
                               uint iid [[instance_id]],
                               constant Ut *lineIndices [[buffer(3)]],
                               uint vid [[ vertex_id ]])
{
    uint lineIndex1=lineIndices[iid].position.x;
    uint lineIndex2=lineIndices[iid].position.y;
    
    Point out = points[lineIndex1];
    float scale = transform.scale;
    float2 offset = transform.offset;
    float2 pos = float2(out.position.x * scale - offset.x, out.position.y * scale - offset.y);
    out.position = uniforms.scaleMatrix * float4(pos, 0, 1);
    
    Point out1 = points[lineIndex2];
    float2 pos1 = float2(out1.position.x * scale - offset.x, out1.position.y * scale - offset.y);
    out1.position = uniforms.scaleMatrix * float4(pos1, 0, 1);
    
    float thickness=0.1;
    float4 position1=out.position;
    float4 position2=out1.position;
    float4 v = position2 - position1;
    float2 p0 = float2(position1.x,position1.y);
    float2 v0 = float2(v.x,v.y);
    float2 v1 = thickness * normalize(v0) * float2x2(float2(0,-1),float2(1,0));
    float2 pa = p0 + v1;
    float2 pb = p0 - v1;
    float2 pc = p0 - v1 + v0;
    float2 pd = p0 + v1 + v0;

    Point outVertex;
    switch(vid)
    {
        case 0:
            outVertex.position = float4(pa.x,pa.y,position1.z,position1.w);
            break;
        case 1:
            outVertex.position = float4(pb.x,pb.y,position1.z,position1.w);
            break;
        case 2:
            outVertex.position = float4(pc.x,pc.y,position2.z,position2.w);
            break;
        case 3:
            outVertex.position = float4(pa.x,pa.y,position1.z,position1.w);
            break;
        case 4:
            outVertex.position = float4(pc.x,pc.y,position2.z,position2.w);
            break;
        case 5:
            outVertex.position = float4(pd.x,pd.y,position2.z,position2.w);
            break;
    }
    outVertex.color = float4(1,0,0,1);
    return outVertex;
};`
emmmm follow your demo, here is my code,
![image](https://user-images.githubusercontent.com/38343165/58723709-5eb6f280-840d-11e9-9136-676b677676e2.png)
any idea to fix this white space?

**Comment by eldade** [comment]
I'm confused. Your code isn't even remotely similar to my original program. If you wanted to do the same thing, why aren't you using the provided sample?
