### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by Yang-Xijie** [eldade/ios_metal_bezier_renderer#5]
I opened this project on Xcode 13 (macOS 12) and got the popover:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/57952362/150673300-654ede0c-c434-4514-ac88-636ccb097e23.png">

**Comment by Yang-Xijie** [comment]
Check the pull request here: https://github.com/eldade/ios_metal_bezier_renderer/pull/6

**Comment by eldade** [comment]
Works great, thanks for getting this done!
