### ISSUE TITLE
makeBuffer(bytesNoCopy: ) is throwing an error in latest swift :(

### ISSUE THREAD

**Issue by bsantanas** [eldade/ios_metal_bezier_renderer#7]
https://github.com/eldade/ios_metal_bezier_renderer/blob/9d8eace043cffa38f0131704c85acafe0875d7b0/metal_bezier/PageAlignedArray.swift#L280

Don't really know how to fix it. Was hoping to use this library to draw line primitives in metal

**Comment by Yang-Xijie** [comment]
What do you mean by "latest swift"? Are you using the beta macOS?

I just cloned the repo and use the latest commit 9d8eace. Built on an M2 Mac (macOS Ventura 13.4) with Swift 5.8 and installed on an iPad (iPadOS 16.5), no error found.

On my Mac:

```
$ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

**Comment by bsantanas** [comment]
thanks for the super quick reply. You're right, it's working correctly. 

The issue was that I was trying to run on a simulator and it doesn't allow some shared storage memory settings, but trying on an iPhone 13 pro works 

sorry for the false positive here, I'm all too new to Metal
